[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run railway:build"]

[start]
cmd = "npm run railway:start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
